JavaScript capstone project
VTY1999/JS-Group-capstone pull request #27
Opened 2022-02-18 11:36 UTC by VTY1999

## Changes made in this PR:
- Create the home page
- Set up the project with Webpack and Jest
- Display comments for a given item on the Comments pop-up
- Display Comments pop up with selected item's details
- Add comments counter
- Add footer
- Add header
- Display the number of likes for each item on the Homepage
- Display list of items on the Homepage
- Create feature: add a new comment
- Create feature: add new like
- Add all items counter on the Homepage
- Add tests for items counter
- Add tests for comments counter

2022-02-18 16:22 UTC, eri8-9 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Required Changes ♻️

- [x] The student recorded a video presenting the features of the project.
  - The maximum length of the video is 5 minutes.
  - The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
  - All the members in the video should appear in the video and talk about the project.
  - The video contains a highlight about a piece of the code the student finds interesting or is proud of making.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 16:22 UTC, eri8-9 commented on src/index.js
> +// });
- [ ] It would be great if we don't have commented code. 😉

2022-02-18 16:22 UTC, eri8-9 commented on src/index.js
> +  // LogoContainer,
- [ ] It would be great if we don't have commented code. 😉

2022-02-18 16:22 UTC, eri8-9 commented on src/index.js
> +// import logoImage from './assets/Logo.png';
- [ ] It would be great if we don't have commented code. 😉

2022-02-18 16:22 UTC, eri8-9 commented on src/index.html
> +        <!-- Logo Image added dynamically via JS -->
- [ ] It would be great if we don't have commented code. 😉

2022-02-18 16:22 UTC, eri8-9 commented on src/index.html
> +      <!-- Movies section generated dynamically -->
- [ ] It would be great if we don't have commented code. 😉

2022-02-19 09:19 UTC, julie-ify requested changes
## Hi @VTY1999 and @SirriRyisa,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

- [x] **[REQUIRED]**  Good job with the video presentation. However, it is required that all the members of the team should appear in the video and talk about the project. The video should contain a highlight about a piece of the code the students find interesting or are proud of making.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 09:32 UTC, VTY1999 commented
My partner said she won't be available today

On Sat, Feb 19, 2022, 10:19 AM Juliana Ifionu ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @VTY1999 <https://github.com/VTY1999> and @SirriRyisa
> <https://github.com/SirriRyisa>,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Required Changes ♻️
>
> *Check the comments under the review.*
>
>    - *[REQUIRED]* Good job with the video presentation. However, it is
>    required that all the members of the team should appear in the video and
>    talk about the project. The video should contain a highlight about a piece
>    of the code the students find interesting or are proud of making.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread and tag me
> @julie-ify if something is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/VTY1999/JS-Group-capstone/pull/27#pullrequestreview-887907431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASBYMWH4P2QEV32M2D4XLXDU35OCRANCNFSM5OXUFTFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-19 09:48 UTC, julie-ify commented
Ok, Please make the other changes and submit okay.

2022-02-19 11:32 UTC, FrederickMih approved these changes
Hi @VTY1999, @SirriRyisa , 

### Congratulations!
![](https://media.giphy.com/media/jxddr3g5t0agpbIwkW/giphy.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-19 11:40 UTC, merged